---
title="de-2"
---
<br>

## <span class="top"> で　ニ </span>

<br>

1*.* おれは自分の目で見たことを信じる男なんだ。

<audio src="05/de-2-01.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

I believe what I see with my own eyes.

</div>

<hr>


2*.* わたしは頭痛がすると言って一人で帰って来ました。

<audio src="05/de-2-02.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

I said I had a headache and came back alone.

</div>

<hr>


3*.* なにかの理由で彼はもどってきませんでした。

<audio src="05/de-2-03.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

For some reason or other he had not returned.

</div>

<hr>


4*.* 二人はふるえる指でそれを拡げた。紙は白紙だった！

<audio src="05/de-2-04.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

With trembling fingers they unfolded it. The sheet was blank!

</div>

<hr>


5*.* あたりの雰囲気は、棺のにおいでよごされている感じだった。

<audio src="05/de-2-05.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

The atmosphere seemed tainted with the smell of coffins.

</div>

<hr>


6*.* だれがこの遺言書を燃やしたのだ？何の目的で？

<audio src="05/de-2-06.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

Who destroyed this will? And what was their object?

</div>

<hr>


7*.* あなたのことでなにか妙な噂が流されているのですね。

<audio src="05/de-2-07.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

There is evidently some story being circulated about you.

</div>

<hr>


8*.* そうはいっても、わたし、あることで、ひどく悩んでいます。

<audio src="05/de-2-08.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

But all the same, I’m sorely troubled about something.

</div>

<hr>


9*.* インターネットで花を注文して、確認メールを受け取った。

<audio src="05/de-2-09.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

I ordered flowers online and received a confirmation by email.

</div>

<hr>


10*.* だから僕は、先祖伝来のものおよび、労力で得たものを尊重するのだ。

<audio src="05/de-2-10.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

That’s why I prize what’s come to me from my ancestors or been won by hard work.

</div>

<hr>


11*.* 震える指で、彼女は封筒を開けた。

<audio src="05/de-2-11.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

She opened the envelope with her trembling fingers.

</div>

<hr>


12*.* 今の雷でどこかの電線が切れた。

<audio src="05/de-2-12.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

That lightning just now cut one of the power lines.

</div>

<hr>


13*.* 彼は人気のない海岸に一人で立っている。

<audio src="05/de-2-13.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">


He stood alone on the quiet beach.
</div>

<hr>


14*.* なんであの人あんな格好で車内うろついてんの？

<audio src="05/de-2-14.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

Why is he wandering around the train looking like that?

</div>

<hr>


15*.* 青年は乾いた砂の上で足のしずくを払った。


<audio src="05/de-2-15.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

The young man stamped on the dry sand to shake off the wet.

</div>

<hr>


16*.* 何がきっかけでそんな恐ろしい光景を見たのか、心当たりはありますか？


<audio src="05/de-2-16.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

Any idea what might have sparked such a frightening vision?

</div>

<hr>


17*.* こんな重い物を一人で動かすには相当骨が折れます。

<audio src="05/de-2-17.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

It’d be hard for one person to move something this heavy around.

</div>

<hr>


18*.* 部屋はたちまち火と煙で埋まりました。

<audio src="05/de-2-18.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

The room was filled with fire and smoke.

</div>

<hr>


19*.* あなたの危険な冒険旅行には、連れは一人では足りませんよ。

<audio src="05/de-2-19.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

You will need more than one companion in your dangerous adventure.

</div>

<hr>


20*.* 地元のコミュニティが設立したこのセンターは、寄付金で運営されています。

<audio src="05/de-2-20.mp3" preload="auto"></audio>

<button class="show-english">英語</button>
<div class="english">

The community here set up this center, which is run on donations.

</div>

