---
pagetitle: "レベル　五"
---
<br>

# レベル　五

<div class="container">

 [授業 一](N5/01-desu.html)　です

 [授業 ニ](N5/02-dake.html)　だけ

 [授業 三](N5/03-darou.html)　だろう

 [授業 四](N5/04-de-1.html)　で 一

 [授業 五](N5/05-de-2.html)　で ニ

 [授業 六](N5/06-deshou.html)　でしょう

 [授業 七](N5/07-ga-1.html)　が 一

 [授業 八](N5/08-ga-2.html)　が ニ

 [授業 九](N5/09-gaaru.html)　がある

 [授業 十](N5/10-gairu.html)　がいる

 [授業 十一](N5/11-hougaii-1.html)　ほうがいい 一

 [授業 十ニ](N5/12-hougaii-2.html)　はうがいい ニ

 [授業 十三](N5/13-ichiban.html)　一番

 [授業 十四](N5/14-ka-1.html)　か 一

 [授業 十五](N5/15-ka-2.html)　か ニ

 [授業 十六](N5/16-kara-1.html)　から 一

 [授業 十七](N5/17-kara-2.html)　から ニ

 [授業 十八](N5/18-kedo.html)　けど
 
 [授業 十九](N5/19-kurai.html)　くらい
 
 [授業 二十](N5/20-mada.html)　まだ

 [授業 二十一](N5/21-made.html)　まで
 
 [授業 二十二](N5/22-maeni.html)　前に
 
 [授業 二十三](N5/23-masenka.html)　ませんか
 
 [授業 二十四](N5/24-mashou.html)　ましょう
 
 [授業 二十五](N5/25-mo.html)　も
 
 [授業 二十六](N5/26-mou.html)　もう

 [授業 二十七](N5/27-na.html)　な
 
 [授業 二十八](N5/28-naidekudesai.html)　ないでくでさい
 
 [授業 二十九](N5/29-naru.html)　なる
 
 [授業 三十](N5/30-ni.html)　に
 
 [授業 三十一](N5/31-ni-e.html)　に・へ
 
 [授業 三十二](N5/32-ni-iku.html)　にいく
 
 [授業 三十三](N5/33-nisuru.html)　にする
 
 [授業 三十四](N5/34-no-1.html)　の
 
 [授業 三十五](N5/35-no-2.html)　の一
 
 [授業 三十六](N5/36-node.html)　ので
 
 [授業 三十七](N5/37-nogajouzu.html)　のがじょうず
 
 [授業 三十八](N5/38-nogasuki.html)　のがすき
 
 [授業 三十九](N5/39-nogaheta.html)　のがへた
 
 [授業 四十](N5/40-tai.html)　たい
 
 [授業 四十一](N5/41-tokotogaaru.html)　とごとがある
 
 [授業 四十二](N5/42-teiru.html)　ている
 
 [授業 四十三](N5/43-tekudasai.html)　てください
 
 [授業 四十四](N5/44-temoii.html)　てもいい
 
 [授業 四十五](N5/45-tekara.html)　てから
 
 [授業 四十六](N5/46-tewaikenai.html)　てわいけない
 
 [授業 四十七](N5/47-to.html)　と
 
 [授業 四十八](N5/48-tsumorida.html)　つもりだ
 
 [授業 四十九](N5/49-ya.html)　や
 
 [授業 五十](N5/50-yori-nohouga.html)　より～のほうが
 
</div>
